language: nodejs
node_js:
- 6.1.x
before_install:
- curl -s -o $HOME/.nvm/nvm.sh https://raw.githubusercontent.com/creationix/nvm/v0.31.0/nvm.sh
- source $HOME/.nvm/nvm.sh
- nvm install stable
- node --version
install:
- npm install
script:
- npm run lint
- node package.js
- npm run build:dll
- npm run build
notifications:
  slack:
    secure: ccL5icbs/Y54xKCpIa4Q4XStQ08S5zMD9Y3MPTp0JN7+rg0KZgOm/a7fgMptdTY88yd9SaI9UQ4L28Mls+KDKgUDs1/BqGKVAcnwtqq4mCZvmIHxDvUODoJnIpHjF8Qt+8tgxpuAveZ6BspTmo7jh4LNrtdPMX2dww/v/gxBOx2rWyAQTUiufMKuhJez7DXl7EHH5XHMqtqCIvKk8dQ7zm7Oetan+4zx/h9ISkarAs68Q+P2kKPL2lm2sUdhUdX8ClCyMl4CYSqkGqbYTMqLXd5UvQnhpH+iwxqlZsRPA5zvloMl7lJHT+2KGZEu2ZsiuJYwVKI7gujeZzO9W+EopIlMNsc+VNeRKvqeble8p/WFqEYgBnFDcNklBhd2iF0IGamniHaKdjOEMr7NG/Y5yy7HDAJ86oFOEMxlFbruj00V58Gk/HSjn2yPuawciRspA0ocJTATb/pXWST8NjyQMpPWRjioqyV23W2YFFJDaPJRNxZQ3pYifunK1l29cimBgS6JxQDqqSrv1ozAzP9b5KjgBQfqgNpeDyJCVwpGCnZmXnJm2YwSUPhhpogGdkUhjYriKXaZeedpu8zfVn4Mmd56tAqLViQMDAGo36qgHS4A2B8p6n6mAZFnGVPE4bTJQibsZpH0sspcJJXKck1znLaeknR7kV8vniEHkPT/Rog=
