dist: trusty
sudo: true
language: nodejs
node_js:
- '7'
cache:
  directories:
  - $HOME/.electron
  - node_modules
install:
- npm install
script:
- npm run lint
- npm run build:dll
- npm run build
notifications:
  slack:
    secure: ccL5icbs/Y54xKCpIa4Q4XStQ08S5zMD9Y3MPTp0JN7+rg0KZgOm/a7fgMptdTY88yd9SaI9UQ4L28Mls+KDKgUDs1/BqGKVAcnwtqq4mCZvmIHxDvUODoJnIpHjF8Qt+8tgxpuAveZ6BspTmo7jh4LNrtdPMX2dww/v/gxBOx2rWyAQTUiufMKuhJez7DXl7EHH5XHMqtqCIvKk8dQ7zm7Oetan+4zx/h9ISkarAs68Q+P2kKPL2lm2sUdhUdX8ClCyMl4CYSqkGqbYTMqLXd5UvQnhpH+iwxqlZsRPA5zvloMl7lJHT+2KGZEu2ZsiuJYwVKI7gujeZzO9W+EopIlMNsc+VNeRKvqeble8p/WFqEYgBnFDcNklBhd2iF0IGamniHaKdjOEMr7NG/Y5yy7HDAJ86oFOEMxlFbruj00V58Gk/HSjn2yPuawciRspA0ocJTATb/pXWST8NjyQMpPWRjioqyV23W2YFFJDaPJRNxZQ3pYifunK1l29cimBgS6JxQDqqSrv1ozAzP9b5KjgBQfqgNpeDyJCVwpGCnZmXnJm2YwSUPhhpogGdkUhjYriKXaZeedpu8zfVn4Mmd56tAqLViQMDAGo36qgHS4A2B8p6n6mAZFnGVPE4bTJQibsZpH0sspcJJXKck1znLaeknR7kV8vniEHkPT/Rog=
before_deploy:
- curl https://raw.githubusercontent.com/electron-userland/electron-packager/master/test/ci/before_install.sh | bash 
- node package.js
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: qy3DYgGs7E5SjUgiwprRMCsNmn6RLPQhDjCdc1E6MHS6gUcpTKP4f7cDlEgbsx4szMeexOhzrwb7bKTrvGhDziMHqBOgQie6ZUFtl3j/q0JPfD/9//r5DMF4QuMwuIszL+mjEbd0K/VzebLxrFYt8tyBonSGoJPeNTQs5xbRokU7BgQ3UbjRAKtWYiwnBqPoQymAueYTkwOsqwjuzQm4F/ukcVfnl5Gb4RZhyGsYjJDKhtJHcfLH+z/YpEZEzhw2vD+BHxJbc6QCaENwDtiHVtzQ0ekIm4JTv1sl2xj7nCTITmD4NeM94PAyhB5OQWNt5a10YQNbjFZW2PsqzA1IhCVXK1IhTg8dE0VDXA/4wncHh4mlB1jzPWBijSkZDcPaojLjrRDC3R/kFivsor1MXuIUc9pomn8ovOg9jFTM7kwa3k2ouvm39emddte5W8MFF0OkndsTT3bpCgbKk7w7j6aQNMy3cTD8E1bxcQIxcNYxJ5yww7kyTgVWFm+mauYOjvFqys7VbhKS9Y/KQst2Z7Vltf+A5XhMMB6qkEb2it062AY50u9ZshLP70SUahLghYiFuJW1gMTUlp5SzxRrEeIqFyqJ06yRSGlHVH5E7VCsDFyHBdjJaJj4AHnCxbbgY73T44poKhrkPmgKh5Ce9oAYzX57fGyQ/0ClhlZ0UC4=
  file_glob: true
  file: dist/*.zip
  on:
    tags: true
